package com.martin.integrationframe.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.martin.integrationframe.model.DaoModel;

import com.martin.integrationframe.greendao.DaoModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig daoModelDaoConfig;

    private final DaoModelDao daoModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        daoModelDaoConfig = daoConfigMap.get(DaoModelDao.class).clone();
        daoModelDaoConfig.initIdentityScope(type);

        daoModelDao = new DaoModelDao(daoModelDaoConfig, this);

        registerDao(DaoModel.class, daoModelDao);
    }
    
    public void clear() {
        daoModelDaoConfig.clearIdentityScope();
    }

    public DaoModelDao getDaoModelDao() {
        return daoModelDao;
    }

}
